"use client"

import * as React from "react"
import { createContext, useContext, useEffect, useState } from "react"

type Language = "es" | "en"

type LanguageProviderProps = {
  children: React.ReactNode
  defaultLanguage?: Language
  storageKey?: string
}

type LanguageProviderState = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

// Diccionario de traducciones
const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.about": "Nosotros",
    "nav.services": "Servicios",
    "nav.cases": "Casos de éxito",
    "nav.contact": "Contacto",
    "nav.getStarted": "Comenzar",
    
    // Hero
    "hero.hudLabel": "Ilustración de sistema · interfaz",
    "hero.tagline": "Agencia de Inteligencia Artificial",
    "hero.title": "Transformamos ideas en",
    "hero.titleHighlight": "soluciones digitales",
    "hero.subtitle": "Automatización inteligente, desarrollo de software y estrategias de marketing potenciadas por IA para empresas que buscan liderar en la era digital.",
    "hero.cta.primary": "Iniciar Proyecto",
    "hero.cta.secondary": "Conocer Más",
    "hero.stats.projects": "Proyectos Exitosos",
    "hero.stats.clients": "Clientes Globales",
    "hero.stats.satisfaction": "Satisfacción",
    
    // Services (página dedicada — alineada con Nosotros)
    "services.title": "Nuestros Servicios",
    "services.subtitle": "Soluciones integrales de IA para cada etapa de tu transformación digital",
    "services.heroBadge": "Soluciones AI integrales",
    "services.heroTitle": "Nuestros",
    "services.heroTitleHighlight": "Servicios",
    "services.heroSubtitle":
      "Combinamos estrategia, diseño y tecnología como en nuestra historia: software, automatización e IA aplicada al crecimiento. Aquí tienes las líneas con las que acompañamos a empresas que buscan transformación digital con ejecución medible.",
    "services.bridgeLabel": "Coherencia con Codifikai",
    "services.bridgeTitle": "De la visión al producto — mismos principios que en Nosotros",
    "services.bridgeDesc":
      "Creemos en tecnología que va más allá de lo funcional: soluciones con mentalidad de crecimiento, enfoque empresarial y estética que transmite innovación y confianza. Organizamos el catálogo en cuatro grandes áreas para que encuentres rápido qué encaja con tu etapa.",
    "services.pillar1Title": "Producto y plataformas",
    "services.pillar1Desc":
      "Webs, apps y software a medida con IA integrada, arquitectura escalable y foco en experiencia de usuario y resultados.",
    "services.pillar2Title": "Presencia digital ágil",
    "services.pillar2Desc":
      "Sitios corporativos, landings e integraciones low-code para lanzar y validar con velocidad sin sacrificar calidad.",
    "services.pillar3Title": "Crecimiento y operaciones",
    "services.pillar3Desc":
      "Marketing y ventas con IA, prospección B2B, agentes autónomos y datos para decisiones más claras.",
    "services.navLabel": "Explorar por área",
    "services.bridgeDivider": "Líneas de servicio",
    "services.divider.development": "Desarrollo AI",
    "services.divider.lowcode": "Low-code / no-code",
    "services.divider.marketing": "Marketing & ventas",
    "services.divider.automation": "Automatización AI",
    "services.divider.cta": "Siguiente paso",
    "services.ctaTitle": "¿Listo para transformar tu negocio?",
    "services.ctaSubtitle":
      "Agenda una consultoría gratuita y descubre qué combinación de servicios encaja con tus objetivos.",
    "services.ctaPrimary": "Agendar consultoría",
    "services.development.title": "Desarrollo AI",
    "services.development.desc":
      "Aplicaciones web, móviles y software empresarial con IA embebida, listos para escalar.",
    "services.development.web": "Webs AI",
    "services.development.apps": "Apps AI",
    "services.development.software": "Software AI",
    "services.marketing.title": "Marketing & Ventas AI",
    "services.marketing.desc": "Prospección B2B, ventas inteligentes y embudos automatizados con datos.",
    "services.marketing.prospecting": "Prospección B2B con IA",
    "services.marketing.sales": "Sistema de ventas con IA",
    "services.automation.title": "Automatización empresarial AI",
    "services.automation.desc": "Agentes, flujos y modelos para operar con menos fricción y más claridad.",
    "services.automation.agents": "Agentes IA autónomos",
    "services.automation.data": "Datos y modelos AI",
    "services.learnMore": "Conocer más",
    "services.lowcode.title": "Low-Code / No-Code",
    "services.lowcode.desc": "Sitios corporativos, landings e integraciones con herramientas low-code.",
    "services.lowcode.corporate": "Sitios web corporativos",
    "services.lowcode.landing": "Landing pages",
    "services.lowcode.integrations": "Integraciones low-code",
    "services.devWeb.desc":
      "Sitios web inteligentes con personalización dinámica, chatbots integrados y SEO asistido por IA.",
    "services.devWeb.f1": "Diseño UX/UI adaptativo",
    "services.devWeb.f2": "Chatbots conversacionales",
    "services.devWeb.f3": "SEO automatizado con IA",
    "services.devWeb.f4": "Analytics predictivo",
    "services.devWeb.f5": "CMS con IA generativa",
    "services.devApps.desc":
      "Apps nativas e híbridas con machine learning, experiencias personalizadas y rendimiento sólido.",
    "services.devApps.f1": "iOS y Android",
    "services.devApps.f2": "Reconocimiento de voz e imagen",
    "services.devApps.f3": "Notificaciones inteligentes",
    "services.devApps.f4": "Personalización por usuario",
    "services.devApps.f5": "Capacidades AI offline",
    "services.devSoft.desc":
      "Soluciones empresariales a medida: automatización, datos y APIs robustas.",
    "services.devSoft.f1": "Arquitectura escalable",
    "services.devSoft.f2": "Integración con sistemas legacy",
    "services.devSoft.f3": "APIs REST y GraphQL",
    "services.devSoft.f4": "Procesamiento de grandes volúmenes de datos",
    "services.devSoft.f5": "Seguridad enterprise",
    "services.lcCorp.desc":
      "Sitios corporativos con diseño premium, optimizados para conversión y posicionamiento.",
    "services.lcCorp.f1": "Diseño premium personalizado",
    "services.lcCorp.f2": "Optimizado para SEO",
    "services.lcCorp.f3": "Carga rápida",
    "services.lcCorp.f4": "Panel de administración claro",
    "services.lcCorp.f5": "Integraciones con CRM",
    "services.lcLand.desc":
      "Landings de alta conversión con experimentación, analítica y optimización continua.",
    "services.lcLand.f1": "Diseño orientado a conversión",
    "services.lcLand.f2": "A/B testing integrado",
    "services.lcLand.f3": "Formularios inteligentes",
    "services.lcLand.f4": "Rendimiento optimizado",
    "services.lcLand.f5": "Integraciones de marketing",
    "services.lcInt.desc":
      "Automatización de flujos y conexiones entre herramientas con plataformas low-code.",
    "services.lcInt.f1": "Automatizaciones Zapier y Make",
    "services.lcInt.f2": "Integraciones Airtable y Notion",
    "services.lcInt.f3": "Workflows a medida",
    "services.lcInt.f4": "Conexiones API",
    "services.lcInt.f5": "Sincronización de datos",
    "services.mktPros.desc":
      "Prospección automatizada que identifica, califica y nutre leads B2B de alto valor.",
    "services.mktPros.f1": "Definición de lead ideal",
    "services.mktPros.f2": "Scoring predictivo",
    "services.mktPros.f3": "Secuencias automatizadas",
    "services.mktPros.f4": "Integración con CRM",
    "services.mktPros.f5": "Reportes de conversión",
    "services.mktSales.desc":
      "Ventas asistidas por IA: forecasting, pipeline y propuestas con menos fricción.",
    "services.mktSales.f1": "Asistentes de ventas con IA",
    "services.mktSales.f2": "Forecasting predictivo",
    "services.mktSales.f3": "Optimización de precios",
    "services.mktSales.f4": "Análisis de conversaciones",
    "services.mktSales.f5": "Automatización de propuestas",
    "services.autoAgents.desc":
      "Agentes que ejecutan tareas complejas de forma autónoma: soporte, operaciones y más.",
    "services.autoAgents.f1": "Atención multicanal 24/7",
    "services.autoAgents.f2": "Procesamiento de documentos",
    "services.autoAgents.f3": "Decisiones asistidas",
    "services.autoAgents.f4": "Escalamiento inteligente",
    "services.autoAgents.f5": "Aprendizaje continuo",
    "services.autoData.desc":
      "Pipelines, modelos y dashboards para ventas, marketing y operaciones.",
    "services.autoData.f1": "Data pipelines automatizados",
    "services.autoData.f2": "Modelos ML a medida",
    "services.autoData.f3": "Análisis predictivo",
    "services.autoData.f4": "Dashboards en tiempo real",
    "services.autoData.f5": "Gobernanza de datos",
    
    // About
    "about.title": "Sobre Nosotros",
    "about.subtitle": "Somos la Agencia de IA para Empresas",
    "about.description": "Combinamos experiencia técnica con visión estratégica para crear soluciones de inteligencia artificial que generan resultados medibles.",
    "about.mission.title": "Nuestra Misión",
    "about.mission.desc": "Democratizar el acceso a la inteligencia artificial para empresas de todos los tamaños.",
    "about.vision.title": "Nuestra Visión",
    "about.vision.desc": "Ser el socio tecnológico de referencia en transformación digital mediante IA.",
    "about.values.title": "Valores",
    "about.values.innovation": "Innovación Continua",
    "about.values.excellence": "Excelencia Técnica",
    "about.values.transparency": "Transparencia Total",
    "about.values.commitment": "Compromiso con Resultados",
    "about.cta": "Habla con un Asesor",
    "about.heroBadge": "Agencia de desarrollo de software e IA en Colombia",
    "about.heroTitle": "Una fábrica de",
    "about.heroTitleHighlight": "transformación digital",
    "about.heroDesc": "En Codifikai entendemos que las empresas necesitan algo más que tecnología: necesitan visión, ejecución y soluciones que impulsen crecimiento real. Diseñamos experiencias digitales que conectan estrategia, producto y resultados.",
    "about.essence": "Nuestra esencia",
    "about.history": "Historia",
    "about.historyP1": "Todo comenzó con una idea clara: las personas y las empresas necesitan socios tecnológicos capaces de evolucionar al ritmo del mercado y convertir los retos en oportunidades reales.",
    "about.historyP2": "Así nació Codifikai, con la intención de crear software, automatizaciones y soluciones digitales que no solo resuelvan una necesidad puntual, sino que también fortalezcan la visión de negocio de cada cliente.",
    "about.historyP3": "Nuestro enfoque combina estrategia, diseño y tecnología para construir experiencias modernas, funcionales y preparadas para escalar.",
    "about.vision": "Nuestra visión",
    "about.visionDesc": "Creemos en una tecnología que vaya más allá de lo funcional. Por eso construimos soluciones con mentalidad de crecimiento, enfoque empresarial y una estética capaz de transmitir innovación, confianza y alto nivel profesional.",
    "about.innovation": "Innovación estratégica",
    "about.premium": "Experiencias premium",
    "about.scalable": "Soluciones escalables",
    "about.purpose": "Tecnología con propósito",
    "about.learnMore": "¿Quieres saber más?",
    "about.brandTransition": "Transición de marca",
    "about.brandDesc": "De la visión estratégica pasamos al rostro que lidera la ejecución, la confianza y la construcción de la marca.",
    "about.founderLeadership": "Liderazgo fundador",
    "about.leadershipTitle": "El liderazgo que convierte visión en resultados reales",
    "about.founderMessage": "En sus palabras",
    "about.benefit1": "Equipo multidisciplinario con +50 años de experiencia combinada",
    "about.benefit2": "Metodologías ágiles adaptadas a cada proyecto",
    "about.benefit3": "Soporte continuo 24/7 post-implementación",
    "about.benefit4": "Garantía de satisfacción en todos los proyectos",
    "about.whyChoose": "Por qué elegirnos",
    "about.experience": "Experiencia de",
    "about.trust": "Confianza",
    "about.experienceDesc": "Más de una década de experiencia nos respalda. Hemos ayudado a empresas de todos los tamaños a transformar sus operaciones con inteligencia artificial.",
    "about.competitiveAnalysis": "Análisis Competitivo",
    "about.deliveryTime": "Tiempo de entrega",
    "about.deliveryValue": "2x más rápido",
    "about.costVsAgencies": "Costo vs. agencias tradicionales",
    "about.costValue": "-40% promedio",
    "about.retention": "Tasa de retención de clientes",
    "about.retentionValue": "94%",
    "about.nps": "NPS Score",
    "about.npsValue": "78",
    "about.techTitle": "Tecnologías",
    "about.techIntro1": "En Codifikai combinamos herramientas consolidadas del ecosistema digital con tecnologías modernas orientadas a rendimiento, seguridad y escalabilidad.",
    "about.techIntro2": "Elegimos cada stack en función del contexto del proyecto, la madurez técnica y los objetivos del negocio. Eso nos permite construir soluciones más sólidas, más mantenibles y mejor preparadas para crecer.",
    "about.techPerf": "Rendimiento optimizado desde la arquitectura hasta la experiencia final del usuario.",
    "about.techSecurity": "Seguridad y estabilidad como base para productos confiables y escalables.",
    "about.techFlex": "Flexibilidad tecnológica para adaptarnos a distintos tamaños de empresa y etapas de crecimiento.",
    "about.techSelect": "Selección estratégica de herramientas para equilibrar velocidad, calidad y sostenibilidad.",
    "about.techFrontendTitle": "Tecnologías Frontend",
    "about.techFrontendDesc": "Diseñamos interfaces digitales modernas, rápidas y orientadas a conversión. Desde experiencias web corporativas hasta productos interactivos, trabajamos el frontend con foco en rendimiento, claridad visual y experiencia de usuario.",
    "about.techFrontendStack": "React.js - Next.js - Angular - Flutter",
    "about.techBackendTitle": "Tecnologías Backend",
    "about.techBackendDesc": "Construimos bases sólidas para productos escalables y seguros. Desarrollamos arquitecturas backend preparadas para integraciones, automatización de procesos y operación estable en entornos empresariales.",
    "about.techBackendStack": "Node.js - PHP - .NET - APIs REST",
    "about.techDataTitle": "Ciencia de Datos",
    "about.techDataDesc": "Convertimos datos en decisiones más inteligentes. Diseñamos flujos de análisis, limpieza y explotación de información que permiten descubrir oportunidades, optimizar procesos y respaldar estrategias con evidencia.",
    "about.techDataStack": "Python - Pandas - ETL - Analítica predictiva",
    "about.techCmsTitle": "Gestores de Contenido",
    "about.techCmsDesc": "Implementamos plataformas de contenido pensadas para equipos que necesitan autonomía, organización y escalabilidad. Optimizamos la administración digital para que la operación diaria sea más eficiente y profesional.",
    "about.techCmsStack": "WordPress - Headless CMS - Webflow - Shopify",
    "about.ctaSectionLabel": "Cierre estratégico",
    "about.ctaTitle": "Somos la Agencia IA para las Empresas",
    "about.ctaDesc": "Conecta con un asesor especializado y descubre cómo podemos transformar tu negocio con soluciones de inteligencia artificial a medida.",
    "about.techCapability": "Capacidad tecnológica",
    "about.institutionalProfile": "Perfil institucional",
    "about.competitiveAdvantage": "Ventaja competitiva",
    "about.founder1Label": "Visión, estrategia y crecimiento",
    "about.founder1Bio": "Como CEO & Founder de Codifikai, lidero una visión enfocada en construir soluciones digitales que conecten innovación, ejecución y resultados de negocio. Creo firmemente que la tecnología debe sentirse cercana, útil y capaz de impulsar una evolución real para cada empresa que confía en nosotros.",
    "about.founder1Quote": "No construimos solo software: construimos confianza, evolución y oportunidades reales de crecimiento.",
    "about.founder2Label": "Estrategia, expansión y dirección comercial",
    "about.founder2Bio": "Como Co-Founder & Strategy Director de Codifikai, impulso una visión enfocada en el crecimiento sostenible, la claridad estratégica y la construcción de relaciones sólidas con cada cliente. Mi enfoque está en alinear negocio, posicionamiento y ejecución para que cada solución genere impacto real y fortalezca la evolución de la marca.",
    "about.founder2Quote": "Una estrategia bien dirigida convierte las ideas en oportunidades y las oportunidades en crecimiento real.",
    "about.founder3Label": "Desarrollo comercial y alianzas",
    "about.founder3Bio": "Como Business Development Manager, lidera la prospección de cuentas, la estructuración de propuestas de valor y el fortalecimiento de relaciones con partners y clientes. Su enfoque conecta necesidades de negocio con soluciones tecnológicas escalables.",
    "about.founder3Quote": "Cada relación comercial sólida es una puerta a proyectos que transforman empresas.",
    
    // CTA
    "cta.title": "Transforma tu negocio con IA",
    "cta.subtitle": "Agenda una consultoría gratuita y descubre cómo la inteligencia artificial puede impulsar tu empresa.",
    "cta.button": "Agendar Consultoría",
    "cta.available": "Disponible ahora",
    
    // Footer
    "footer.description": "Agencia de Inteligencia Artificial especializada en desarrollo, marketing y automatización empresarial.",
    "footer.services": "Servicios",
    "footer.company": "Empresa",
    "footer.contact": "Contacto",
    "footer.legal": "Legal",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.rights": "Todos los derechos reservados.",
    "footer.ctaTitle": "Listos para trabajar juntos",
    "footer.ctaButton": "Hablemos",
    "footer.linksHeading": "Enlaces",
    "footer.writeUs": "Escríbenos",
    "footer.emailJobs": "Empleos y talento",
    "footer.linkAbout": "Quiénes somos",
    "footer.linkServices": "Servicios",
    "footer.linkBlog": "Blog",
    "footer.linkSecurity": "Política de seguridad y protección de la información",
    
    // Process
    "process.title": "Nuestro Proceso",
    "process.subtitle": "Metodología ágil para resultados extraordinarios",
    "process.step1.title": "Descubrimiento",
    "process.step1.desc": "Analizamos tu negocio, objetivos y desafíos para crear una estrategia personalizada.",
    "process.step2.title": "Estrategia",
    "process.step2.desc": "Diseñamos la arquitectura de solución y definimos el roadmap de implementación.",
    "process.step3.title": "Desarrollo",
    "process.step3.desc": "Construimos la solución con tecnología de vanguardia y metodologías ágiles.",
    "process.step4.title": "Lanzamiento",
    "process.step4.desc": "Desplegamos, monitoreamos y optimizamos para asegurar el éxito continuo.",
    
    // Testimonials
    "testimonials.title": "Lo Que Dicen Nuestros Clientes",
    "testimonials.subtitle": "Resultados que hablan por sí mismos",
    
    // Team
    "team.label": "Liderazgo",
    "team.title": "Nuestro Equipo",
    "team.subtitle": "Expertos en tecnología e innovación",
    "team.viewProfile": "Ver perfil",
    "team.jhoanBio": "Lidera la visión de Codifikai con foco en crecimiento, ejecución y soluciones digitales alineadas al negocio.",
    "team.jhonBio": "Impulsa la estrategia, la expansión comercial y la dirección de iniciativas con impacto real y sostenible.",
    "team.roleBDM": "Gerente de Desarrollo de Negocios",
    "team.victorBio": "Impulsa alianzas estratégicas, nuevas oportunidades comerciales y la expansión de Codifikai en mercados clave, alineando relaciones con clientes con la visión de producto y crecimiento.",
    
    // Partners
    "partners.title": "Marcas que Confían en Nosotros",
    "partners.subtitle": "Representaciones comerciales y alianzas estratégicas",
    
    // Case Studies
    "cases.label": "Casos destacados",
    "cases.title": "Casos de Éxito",
    "cases.subtitle": "Proyectos que generan impacto real",
    "cases.viewAll": "Ver todos los casos",

    // Globe / Alcance global
    "globe.label": "Alcance global",
    "globe.badge": "Desde Colombia hacia el mundo",
    "globe.title": "Proyectos y clientes en múltiples continentes",
    "globe.subtitle": "Desarrollamos software, automatizaciones y soluciones IA para empresas en Estados Unidos, Europa, Asia y más. Conectamos visión tecnológica con ejecución global.",
    "globe.fromColombia": "Desde Colombia",
    "globe.towards": "hacia",
    "globe.usaDesc": "Proyectos de software, e-commerce y automatización para clientes en Estados Unidos. Desarrollo web, apps y soluciones IA.",
    "globe.europaDesc": "Plataformas digitales y estrategias de marketing para el mercado europeo. Cumplimiento normativo y escalabilidad.",
    "globe.japonDesc": "Soluciones tecnológicas y sourcing digital para el mercado asiático. Enfoque en calidad y precisión.",
    "globe.chinaDesc": "Desarrollo de software y soluciones de comercio internacional. Integración con ecosistemas digitales asiáticos.",
    "globe.canadaDesc": "Proyectos de software y transformación digital para clientes en Norteamérica. Plataformas escalables.",
    "globe.mexicoDesc": "Desarrollo de software y soluciones digitales para el mercado mexicano. E-commerce, apps y automatización.",
    "globe.brasilDesc": "Plataformas y software para el mercado brasileño. Integración con ecosistemas latinoamericanos.",
    "globe.argentinaDesc": "Soluciones de software y transformación digital para empresas en el Cono Sur.",
    "globe.chileDesc": "Desarrollo tecnológico y soluciones IA para el mercado chileno. Minería, retail y servicios.",
    "globe.peruDesc": "Proyectos digitales y software para empresas peruanas. Comercio y logística.",
    "globe.uaeDesc": "Soluciones tecnológicas para el Golfo. E-commerce, fintech y plataformas B2B.",
    "globe.indiaDesc": "Desarrollo de software y outsourcing tecnológico. Integración con equipos globales.",
    "globe.coreaDesc": "Tecnología y soluciones digitales para el mercado coreano. Innovación y precisión.",
    "globe.australiaDesc": "Software y soluciones IA para el mercado australiano. Comercio y servicios.",
    "globe.statusActive": "Mercado activo",
    "globe.statusExpansion": "En expansión",
    "globe.statusStrategic": "Mercado estratégico",
    "globe.statusGrowth": "En crecimiento",
    "globe.centerColombia": "Centrar en Colombia",
    "globe.usa": "Estados Unidos",
    "globe.europa": "Europa",
    "globe.japon": "Japón",
    "globe.china": "China",
    "globe.canada": "Canadá",
    "globe.mexico": "México",
    "globe.brasil": "Brasil",
    "globe.argentina": "Argentina",
    "globe.chile": "Chile",
    "globe.peru": "Perú",
    "globe.uae": "Emiratos Árabes",
    "globe.india": "India",
    "globe.corea": "Corea del Sur",
    "globe.australia": "Australia",
    "globe.colombiaGlobeLabel": "Colombia · HUB",
    "globe.techMetaColombia": "HUB_CODIFIKAI · region=CO · lat=4.571 · lng=-74.297 · role=primary_edge · TLS=1.3 · status=online",
    "globe.techMetaUsa": "NODE=US-NOAM · uplink=CO⇄US · lat=39.83 · stack=Next.js|Node · cloud=AWS · svc=web·apps·IA·e-commerce · api=REST|GraphQL",
    "globe.techMetaMexico": "NODE=MX-LATAM · uplink=CO⇄MX · stack=React|Nest · svc=web·apps·automatización · deploy=multi-region",
    "globe.techMetaCanada": "NODE=CA-NOAM · uplink=CO⇄CA · stack=TS|Python · svc=plataformas·integración · compliance=PIPEDA",
    "globe.techMetaBrasil": "NODE=BR-LATAM · uplink=CO⇄BR · stack=Node|React · locale=pt-BR · svc=e-commerce·APIs",
    "globe.techMetaArgentina": "NODE=AR-CONO · uplink=CO⇄AR · stack=web|mobile · svc=transformación digital",
    "globe.techMetaChile": "NODE=CL-ANDES · uplink=CO⇄CL · stack=IA|analytics · vertical=retail·minería",
    "globe.techMetaPeru": "NODE=PE-ANDES · uplink=CO⇄PE · svc=logística·comercio · integración=ERP",
    "globe.techMetaEuropa": "NODE=EU-CENTRAL · uplink=CO⇄EU · stack=Next|headless · normativa=GDPR · multi-tenant",
    "globe.techMetaUae": "NODE=AE-GCC · uplink=CO⇄AE · svc=fintech·B2B · latency=optimizada",
    "globe.techMetaIndia": "NODE=IN-APAC · uplink=CO⇄IN · model=equipos distribuidos · stack=full-stack",
    "globe.techMetaChina": "NODE=CN-APAC · uplink=CO⇄CN · integración=comercio·APIs · i18n=zh",
    "globe.techMetaJapon": "NODE=JP-APAC · uplink=CO⇄JP · stack=calidad·precision · svc=B2B",
    "globe.techMetaCorea": "NODE=KR-APAC · uplink=CO⇄KR · stack=web·apps · innovación=alta",
    "globe.techMetaAustralia": "NODE=AU-APAC · uplink=CO⇄AU · svc=software·IA · zona=Oceano",

    // Legal (privacidad / términos)
    "legal.backToHome": "Volver al inicio",
    "legal.contactHint": "Para consultas sobre estos documentos:",
    "legal.privacy.title": "Política de privacidad",
    "legal.privacy.updated": "Última actualización: marzo de 2026",
    "legal.privacy.s1.title": "1. Responsable del tratamiento",
    "legal.privacy.s1.body": "El responsable del tratamiento de los datos personales es Codifikai, en adelante «Codifikai», con domicilio a efectos de notificaciones en Colombia y correo de contacto codifikai@gmail.com.\n\nEl uso de este sitio web y la contratación de servicios puede implicar el tratamiento de datos personales conforme a la legislación aplicable en Colombia (Ley 1581 de 2012 y normas concordantes) y, cuando corresponda, al marco europeo de protección de datos.",
    "legal.privacy.s2.title": "2. Datos que podemos tratar",
    "legal.privacy.s2.body": "Según la interacción con nosotros, podemos tratar datos identificativos y de contacto (nombre, correo electrónico, teléfono, empresa), datos de navegación y técnicos (dirección IP, tipo de dispositivo, navegador, páginas visitadas) y, en su caso, información que nos facilite voluntariamente a través de formularios o comunicaciones.\n\nNo solicitamos datos especialmente protegidos salvo que sea estrictamente necesario y con su consentimiento explícito cuando la ley lo exija.",
    "legal.privacy.s3.title": "3. Finalidades y legitimación",
    "legal.privacy.s3.body": "Tratamos los datos para: gestionar consultas y solicitudes de contacto; prestar y mejorar nuestros servicios de desarrollo de software, automatización e inteligencia artificial; enviar comunicaciones relacionadas con la relación contractual o precontractual cuando exista interés legítimo o consentimiento; cumplir obligaciones legales; y garantizar la seguridad del sitio y la continuidad del servicio.\n\nLa base jurídica puede ser el consentimiento, la ejecución de un contrato, el interés legítimo en la medida aplicable o el cumplimiento de obligaciones legales, según cada tratamiento.",
    "legal.privacy.s4.title": "4. Conservación y comunicación a terceros",
    "legal.privacy.s4.body": "Conservamos los datos el tiempo necesario para cumplir las finalidades descritas y las obligaciones legales. Transcurrido ese plazo, los suprimimos o anonimizamos cuando sea posible.\n\nPodemos recurrir a proveedores de hosting, analítica, correo o herramientas cloud que actúen como encargados del tratamiento bajo instrucciones y medidas contractuales adecuadas. No vendemos sus datos personales a terceros.",
    "legal.privacy.s5.title": "5. Derechos del titular",
    "legal.privacy.s5.body": "Puede ejercer los derechos de conocer, actualizar, rectificar y suprimir sus datos, revocar la autorización o solicitar prueba de la misma, acceder de forma gratuita a sus datos, presentar quejas ante la autoridad competente y las demás que considere la Ley 1581 de 2012 y el decreto reglamentario.\n\nPara ejercer sus derechos, escriba a codifikai@gmail.com indicando el derecho que desea ejercer y su identidad. Podremos solicitar información adicional razonable para verificar su identidad.",
    "legal.privacy.s6.title": "6. Cookies, seguridad y cambios",
    "legal.privacy.s6.body": "Este sitio puede utilizar cookies y tecnologías similares para medir audiencia y mejorar la experiencia. Puede configurar su navegador para rechazar cookies, aunque algunas funciones podrían verse limitadas.\n\nAplicamos medidas técnicas y organizativas razonables para proteger la información. Ningún sistema es 100% seguro.\n\nPodemos modificar esta política; la versión vigente se publicará en esta página con la fecha de actualización indicada arriba.",

    "legal.terms.title": "Términos y condiciones de uso",
    "legal.terms.updated": "Última actualización: marzo de 2026",
    "legal.terms.s1.title": "1. Aceptación",
    "legal.terms.s1.body": "El acceso y uso del sitio web de Codifikai (en adelante, el «Sitio») implica la aceptación de estos términos y condiciones. Si no está de acuerdo, debe abstenerse de utilizar el Sitio.\n\nCodifikai se reserva el derecho de modificar el presente documento en cualquier momento. Los cambios serán efectivos desde su publicación en la web.",
    "legal.terms.s2.title": "2. Identificación y servicios",
    "legal.terms.s2.body": "Codifikai ofrece servicios profesionales de desarrollo de software, automatización, inteligencia artificial y soluciones digitales afines, según lo acordado en cada propuesta o contrato particular.\n\nLos contenidos del Sitio tienen carácter informativo y general. No constituyen asesoramiento jurídico ni garantía de resultados específicos salvo pacto expreso por escrito.",
    "legal.terms.s3.title": "3. Uso permitido",
    "legal.terms.s3.body": "Se compromete a utilizar el Sitio de forma lícita, sin vulnerar derechos de terceros, sin introducir malware ni realizar actividades que puedan dañar, interrumpir o sobrecargar los sistemas.\n\nQueda prohibida la reproducción no autorizada del contenido del Sitio con fines comerciales, la extracción automatizada abusiva (scraping) y cualquier uso que contravenga la ley aplicable o la buena fe.",
    "legal.terms.s4.title": "4. Propiedad intelectual",
    "legal.terms.s4.body": "Los textos, marcas, logotipos, diseño, código y demás elementos del Sitio son protegidos por la legislación aplicable. Los derechos sobre entregables de proyectos se regirán por el contrato correspondiente con cada cliente.\n\nSalvo licencia expresa, no se le otorga ningún derecho de uso sobre los materiales del Sitio más allá de la navegación personal.",
    "legal.terms.s5.title": "5. Limitación de responsabilidad",
    "legal.terms.s5.body": "El Sitio se ofrece «tal cual» y «según disponibilidad». En la medida permitida por la ley, Codifikai no será responsable por daños indirectos, lucro cesante, pérdida de datos o interrupciones derivadas del uso o imposibilidad de uso del Sitio.\n\nLos enlaces a sitios de terceros son meramente informativos; Codifikai no controla los contenidos de esos sitios ni asume responsabilidad por ellos.",
    "legal.terms.s6.title": "6. Ley aplicable y contacto",
    "legal.terms.s6.body": "Salvo disposición imperativa en contrario, las relaciones derivadas del uso del Sitio se interpretarán conforme a la legislación de la República de Colombia. Para controversias, se someterán a los jueces competentes en Colombia, salvo norma especial aplicable.\n\nPara cualquier consulta sobre estos términos: codifikai@gmail.com.",

    // Contact floating
    "contact.title": "¿Hablamos?",
    "contact.subtitle": "Estamos listos para ayudarte a transformar tu negocio",
    "contact.whatsapp": "Respuesta inmediata",
    "contact.email": "codifikai@gmail.com",
    "contact.schedule": "Agendar Llamada",
    "contact.scheduleDesc": "Consultoría gratuita",
    "contact.cta": "Ver más opciones",

    // Services Preview
    "servicesPreview.label": "Servicios",
    "servicesPreview.title": "Soluciones diseñadas para crecer contigo",
    "servicesPreview.subtitle": "Combinamos velocidad, estrategia y ejecución tecnológica para construir soluciones digitales que mejoran procesos, fortalecen marcas y generan crecimiento sostenible.",
    "servicesPreview.lowcode": "Low Code",
    "servicesPreview.lowcodeDesc": "Desarrollamos soluciones digitales ágiles para empresas que necesitan lanzar, validar y optimizar con velocidad, sin sacrificar calidad visual ni estructura profesional.",
    "servicesPreview.software": "Desarrollo de Software",
    "servicesPreview.softwareDesc": "Creamos plataformas, sistemas y productos a medida con arquitectura sólida, enfoque escalable y una implementación alineada con los procesos reales de tu negocio.",
    "servicesPreview.marketing": "Marketing Digital (SEO)",
    "servicesPreview.marketingDesc": "Diseñamos estrategias de posicionamiento y visibilidad digital para atraer tráfico de calidad, fortalecer tu presencia online y generar oportunidades comerciales sostenibles.",
    "servicesPreview.contactLabel": "Contáctanos",
    "servicesPreview.contactTitle": "¿Requieres alguno de estos servicios?",
    "servicesPreview.contactCta": "Contáctanos",

    // Technologies Preview
    "techPreview.label": "Herramientas y stack",
    "techPreview.title": "La tecnología adecuada para construir soluciones sólidas",
    "techPreview.subtitle": "Trabajamos con un stack moderno y estratégico para desarrollar productos digitales, automatizaciones y plataformas preparadas para crecer con tu negocio.",
    "techPreview.viewTools": "Ver herramientas",
    "techPreview.frontend": "Frontend",
    "techPreview.frontendDesc": "Interfaces modernas, rápidas y orientadas a experiencia de usuario.",
    "techPreview.backend": "Backend",
    "techPreview.backendDesc": "Arquitecturas estables, seguras y listas para escalar.",
    "techPreview.datascience": "Ciencia de Datos",
    "techPreview.datascienceDesc": "Modelos, análisis y automatización basados en información útil.",
    "techPreview.cms": "Gestores de Contenido",
    "techPreview.cmsDesc": "Plataformas flexibles para administrar y evolucionar productos digitales.",

    // Company Intro
    "companyIntro.label": "Quiénes somos",
    "companyIntro.badge": "Socios tecnológicos para marcas en evolución",
    "companyIntro.title": "Transformamos ideas y procesos en soluciones digitales con impacto real.",
    "companyIntro.subtitle": "Software, automatización e IA para el crecimiento empresarial. De la estrategia a la ejecución, con productos útiles y listos para escalar.",
    "companyIntro.pillar1": "Desarrollo de software a medida",
    "companyIntro.pillar2": "Automatización y soluciones con IA",
    "companyIntro.pillar3": "Estrategia digital enfocada en crecimiento",
    "companyIntro.stats1": "entregas y despliegues acumulados",
    "companyIntro.stats2": "sectores e industrias atendidas",
    "companyIntro.stats3": "retención y renovación con clientes",
    "companyIntro.cta": "Conocer la empresa",
    "companyIntro.leadership": "Liderazgo y ejecución",
    "companyIntro.cardTag": "Construimos soluciones que conectan tecnología, experiencia de usuario y crecimiento comercial.",

    // Strategy
    "strategy.label": "Nuestra estrategia",
    "strategy.title": "Estrategia de negocio potenciada por IA",
    "strategy.subtitle": "Combinamos experiencia empresarial con tecnología de vanguardia para crear soluciones que transforman operaciones y generan crecimiento sostenible.",
    "strategy.fast": "Implementación Rápida",
    "strategy.fastDesc": "Metodologías ágiles que permiten ver resultados en semanas, no meses.",
    "strategy.security": "Seguridad Empresarial",
    "strategy.securityDesc": "Protocolos de seguridad de nivel enterprise para proteger tus datos.",
    "strategy.scale": "Escalabilidad",
    "strategy.scaleDesc": "Arquitecturas diseñadas para crecer con tu negocio sin límites.",
    "strategy.roi": "ROI Garantizado",
    "strategy.roiDesc": "Medimos y optimizamos constantemente para maximizar tu retorno.",
    "strategy.metricsTitle": "Métricas de Éxito",
    "strategy.metrics1": "Proyectos entregados a tiempo",
    "strategy.metrics2": "Satisfacción del cliente",
    "strategy.metrics3": "Integraciones realizadas",
    "strategy.iso": "ISO 27001 Certificado",
    "strategy.gcp": "Google Cloud Partner",
    "strategy.aws": "AWS Certified",

    // Stats
    "stats.label": "Resultados y confianza",
    "stats.generated": "Generados para clientes",
    "stats.reduction": "Reducción de costos promedio",
    "stats.roi": "ROI promedio en 6 meses",
    "stats.support": "Soporte continuo",
    "stats.testimonial1": "Codifikai transformó nuestra operación de ventas con IA. Los resultados superaron nuestras expectativas.",
    "stats.testimonial2": "La automatización implementada nos ahorró más de 200 horas mensuales en tareas repetitivas.",
    "stats.testimonial3": "Un equipo excepcional que entiende tanto la tecnología como las necesidades del negocio.",

    // Footer links
    "footer.servicesWeb": "Webs AI",
    "footer.servicesApps": "Apps AI",
    "footer.servicesSoftware": "Software AI",
    "footer.servicesMarketing": "Marketing AI",
    "footer.servicesAutomation": "Automatización",
    "footer.companyAbout": "Nosotros",
    "footer.companyCases": "Casos de éxito",
    "footer.companyBlog": "Blog",
    "footer.companyCareers": "Carreras",
    "footer.companyContact": "Contacto",

    // Casos de éxito
    "casesPage.label": "Portafolio",
    "casesPage.title": "Casos de éxito",
    "casesPage.subtitle": "Proyectos que hemos entregado para clientes en comercio internacional, marketplaces, logística y marketing experiencial. Haz clic en cada tarjeta para visitar el sitio.",
    "casesPage.visitSite": "Ver sitio en vivo",
    "casesPage.ctaTitle": "¿Quieres que tu proyecto sea el próximo caso de éxito?",
    "casesPage.ctaButton": "Hablemos de tu proyecto",

    // Features
    "features.strategy": "Estrategia",
    "features.strategyDesc": "Diseñamos soluciones personalizadas basadas en análisis profundo de tu negocio y objetivos.",
    "features.planning": "Planificación",
    "features.planningDesc": "Metodologías ágiles y roadmaps claros para ejecutar proyectos de forma eficiente.",
    "features.growth": "Crecimiento",
    "features.growthDesc": "Soluciones escalables que evolucionan con tu empresa y generan resultados medibles.",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.cases": "Case Studies",
    "nav.contact": "Contact",
    "nav.getStarted": "Get Started",
    
    // Hero
    "hero.hudLabel": "System illustration · interface",
    "hero.tagline": "Artificial Intelligence Agency",
    "hero.title": "We transform ideas into",
    "hero.titleHighlight": "digital solutions",
    "hero.subtitle": "Intelligent automation, software development, and AI-powered marketing strategies for companies looking to lead in the digital era.",
    "hero.cta.primary": "Start Project",
    "hero.cta.secondary": "Learn More",
    "hero.stats.projects": "Successful Projects",
    "hero.stats.clients": "Global Clients",
    "hero.stats.satisfaction": "Satisfaction",
    
    // Services (dedicated page — aligned with About)
    "services.title": "Our Services",
    "services.subtitle": "Comprehensive AI solutions for every stage of your digital transformation",
    "services.heroBadge": "End-to-end AI solutions",
    "services.heroTitle": "Our",
    "services.heroTitleHighlight": "Services",
    "services.heroSubtitle":
      "We combine strategy, design and technology the same way we describe our story: software, automation and AI applied to growth. Here are the lines of work we use to support companies pursuing digital transformation with measurable execution.",
    "services.bridgeLabel": "Aligned with Codifikai",
    "services.bridgeTitle": "From vision to product — same principles as on About",
    "services.bridgeDesc":
      "We believe in technology that goes beyond the functional: solutions with a growth mindset, business focus and an aesthetic that conveys innovation and trust. We group the catalog into four areas so you can quickly find what fits your stage.",
    "services.pillar1Title": "Product & platforms",
    "services.pillar1Desc":
      "Webs, apps and custom software with embedded AI, scalable architecture and a focus on UX and outcomes.",
    "services.pillar2Title": "Agile digital presence",
    "services.pillar2Desc":
      "Corporate sites, landing pages and low-code integrations to launch and validate fast without sacrificing quality.",
    "services.pillar3Title": "Growth & operations",
    "services.pillar3Desc":
      "AI marketing and sales, B2B prospecting, autonomous agents and data for clearer decisions.",
    "services.navLabel": "Browse by area",
    "services.bridgeDivider": "Service lines",
    "services.divider.development": "AI development",
    "services.divider.lowcode": "Low-code / no-code",
    "services.divider.marketing": "Marketing & sales",
    "services.divider.automation": "AI automation",
    "services.divider.cta": "Next step",
    "services.ctaTitle": "Ready to transform your business?",
    "services.ctaSubtitle":
      "Book a free consultation and find out which mix of services fits your goals.",
    "services.ctaPrimary": "Book a consultation",
    "services.development.title": "AI development",
    "services.development.desc":
      "Web, mobile and enterprise software with embedded AI, built to scale.",
    "services.development.web": "AI websites",
    "services.development.apps": "AI apps",
    "services.development.software": "AI software",
    "services.marketing.title": "AI marketing & sales",
    "services.marketing.desc": "B2B prospecting, intelligent sales and data-driven automated funnels.",
    "services.marketing.prospecting": "B2B prospecting with AI",
    "services.marketing.sales": "AI sales system",
    "services.automation.title": "AI business automation",
    "services.automation.desc": "Agents, workflows and models to run with less friction and more clarity.",
    "services.automation.agents": "Autonomous AI agents",
    "services.automation.data": "AI data & models",
    "services.learnMore": "Learn more",
    "services.lowcode.title": "Low-code / No-code",
    "services.lowcode.desc": "Corporate sites, landing pages and integrations with low-code tools.",
    "services.lowcode.corporate": "Corporate websites",
    "services.lowcode.landing": "Landing pages",
    "services.lowcode.integrations": "Low-code integrations",
    "services.devWeb.desc":
      "Intelligent websites with dynamic personalization, embedded chatbots and AI-assisted SEO.",
    "services.devWeb.f1": "Adaptive UX/UI design",
    "services.devWeb.f2": "Conversational chatbots",
    "services.devWeb.f3": "AI-powered SEO automation",
    "services.devWeb.f4": "Predictive analytics",
    "services.devWeb.f5": "Generative CMS workflows",
    "services.devApps.desc":
      "Native and hybrid apps with ML, personalized experiences and solid performance.",
    "services.devApps.f1": "iOS & Android",
    "services.devApps.f2": "Voice and image recognition",
    "services.devApps.f3": "Smart notifications",
    "services.devApps.f4": "Per-user personalization",
    "services.devApps.f5": "Offline AI capabilities",
    "services.devSoft.desc":
      "Custom enterprise solutions: automation, data and robust APIs.",
    "services.devSoft.f1": "Scalable architecture",
    "services.devSoft.f2": "Legacy system integration",
    "services.devSoft.f3": "REST & GraphQL APIs",
    "services.devSoft.f4": "Large-scale data processing",
    "services.devSoft.f5": "Enterprise-grade security",
    "services.lcCorp.desc":
      "Corporate sites with premium design, tuned for conversion and search visibility.",
    "services.lcCorp.f1": "Custom premium design",
    "services.lcCorp.f2": "SEO-optimized",
    "services.lcCorp.f3": "Fast load times",
    "services.lcCorp.f4": "Clear admin dashboards",
    "services.lcCorp.f5": "CRM integrations",
    "services.lcLand.desc":
      "High-converting landing pages with experimentation, analytics and continuous optimization.",
    "services.lcLand.f1": "Conversion-focused design",
    "services.lcLand.f2": "Built-in A/B testing",
    "services.lcLand.f3": "Smart forms",
    "services.lcLand.f4": "Performance-tuned",
    "services.lcLand.f5": "Marketing stack integrations",
    "services.lcInt.desc":
      "Workflow automation and tool connections using low-code platforms.",
    "services.lcInt.f1": "Zapier & Make automations",
    "services.lcInt.f2": "Airtable & Notion integrations",
    "services.lcInt.f3": "Custom workflows",
    "services.lcInt.f4": "API connections",
    "services.lcInt.f5": "Data synchronization",
    "services.mktPros.desc":
      "Automated prospecting that identifies, qualifies and nurtures high-value B2B leads.",
    "services.mktPros.f1": "Ideal customer profiling",
    "services.mktPros.f2": "Predictive scoring",
    "services.mktPros.f3": "Automated sequences",
    "services.mktPros.f4": "CRM integration",
    "services.mktPros.f5": "Conversion reporting",
    "services.mktSales.desc":
      "AI-assisted sales: forecasting, pipeline and proposals with less friction.",
    "services.mktSales.f1": "AI sales assistants",
    "services.mktSales.f2": "Predictive forecasting",
    "services.mktSales.f3": "Pricing optimization",
    "services.mktSales.f4": "Conversation analytics",
    "services.mktSales.f5": "Proposal automation",
    "services.autoAgents.desc":
      "Agents that run complex tasks autonomously: support, operations and more.",
    "services.autoAgents.f1": "24/7 omnichannel support",
    "services.autoAgents.f2": "Document processing",
    "services.autoAgents.f3": "Assisted decisions",
    "services.autoAgents.f4": "Smart escalation",
    "services.autoAgents.f5": "Continuous learning",
    "services.autoData.desc":
      "Pipelines, models and dashboards for sales, marketing and operations.",
    "services.autoData.f1": "Automated data pipelines",
    "services.autoData.f2": "Custom ML models",
    "services.autoData.f3": "Predictive analytics",
    "services.autoData.f4": "Real-time dashboards",
    "services.autoData.f5": "Data governance",
    
    // About
    "about.title": "About Us",
    "about.subtitle": "We Are the AI Agency for Enterprises",
    "about.description": "We combine technical expertise with strategic vision to create artificial intelligence solutions that generate measurable results.",
    "about.mission.title": "Our Mission",
    "about.mission.desc": "Democratize access to artificial intelligence for businesses of all sizes.",
    "about.vision.title": "Our Vision",
    "about.vision.desc": "Be the leading technology partner in digital transformation through AI.",
    "about.values.title": "Values",
    "about.values.innovation": "Continuous Innovation",
    "about.values.excellence": "Technical Excellence",
    "about.values.transparency": "Total Transparency",
    "about.values.commitment": "Commitment to Results",
    "about.cta": "Talk to an Advisor",
    "about.heroBadge": "Software development and AI agency in Colombia",
    "about.heroTitle": "A factory of",
    "about.heroTitleHighlight": "digital transformation",
    "about.heroDesc": "At Codifikai we understand that companies need more than technology: they need vision, execution and solutions that drive real growth. We design digital experiences that connect strategy, product and results.",
    "about.essence": "Our essence",
    "about.history": "History",
    "about.historyP1": "It all started with a clear idea: people and companies need technology partners capable of evolving at the pace of the market and turning challenges into real opportunities.",
    "about.historyP2": "Thus Codifikai was born, with the intention of creating software, automations and digital solutions that not only solve a specific need, but also strengthen the business vision of each client.",
    "about.historyP3": "Our approach combines strategy, design and technology to build modern, functional experiences ready to scale.",
    "about.vision": "Our vision",
    "about.visionDesc": "We believe in technology that goes beyond the functional. That's why we build solutions with a growth mindset, business focus and an aesthetic capable of conveying innovation, trust and high professional level.",
    "about.innovation": "Strategic innovation",
    "about.premium": "Premium experiences",
    "about.scalable": "Scalable solutions",
    "about.purpose": "Technology with purpose",
    "about.learnMore": "Want to know more?",
    "about.brandTransition": "Brand transition",
    "about.brandDesc": "From strategic vision we move to the face that leads execution, trust and brand building.",
    "about.founderLeadership": "Founder leadership",
    "about.leadershipTitle": "The leadership that turns vision into real results",
    "about.founderMessage": "In their words",
    "about.benefit1": "Multidisciplinary team with +50 years of combined experience",
    "about.benefit2": "Agile methodologies adapted to each project",
    "about.benefit3": "24/7 continuous support post-implementation",
    "about.benefit4": "Satisfaction guarantee on all projects",
    "about.whyChoose": "Why choose us",
    "about.experience": "Experience of",
    "about.trust": "Trust",
    "about.experienceDesc": "Over a decade of experience backs us. We have helped companies of all sizes transform their operations with artificial intelligence.",
    "about.competitiveAnalysis": "Competitive Analysis",
    "about.deliveryTime": "Delivery time",
    "about.deliveryValue": "2x faster",
    "about.costVsAgencies": "Cost vs. traditional agencies",
    "about.costValue": "-40% average",
    "about.retention": "Client retention rate",
    "about.retentionValue": "94%",
    "about.nps": "NPS Score",
    "about.npsValue": "78",
    "about.techTitle": "Technologies",
    "about.techIntro1": "At Codifikai we combine proven tools from the digital ecosystem with modern technologies focused on performance, security and scalability.",
    "about.techIntro2": "We choose each stack based on project context, technical maturity and business objectives. This allows us to build more solid, maintainable solutions better prepared to grow.",
    "about.techPerf": "Optimized performance from architecture to end-user experience.",
    "about.techSecurity": "Security and stability as the foundation for reliable and scalable products.",
    "about.techFlex": "Technological flexibility to adapt to different company sizes and growth stages.",
    "about.techSelect": "Strategic tool selection to balance speed, quality and sustainability.",
    "about.techFrontendTitle": "Frontend Technologies",
    "about.techFrontendDesc": "We design modern, fast, conversion-oriented digital interfaces. From corporate web experiences to interactive products, we work on the frontend with a focus on performance, visual clarity and user experience.",
    "about.techFrontendStack": "React.js - Next.js - Angular - Flutter",
    "about.techBackendTitle": "Backend Technologies",
    "about.techBackendDesc": "We build solid foundations for scalable and secure products. We develop backend architectures ready for integrations, process automation and stable operation in enterprise environments.",
    "about.techBackendStack": "Node.js - PHP - .NET - REST APIs",
    "about.techDataTitle": "Data Science",
    "about.techDataDesc": "We turn data into smarter decisions. We design analysis, cleaning and information exploitation flows that enable discovering opportunities, optimizing processes and supporting strategies with evidence.",
    "about.techDataStack": "Python - Pandas - ETL - Predictive analytics",
    "about.techCmsTitle": "Content Management Systems",
    "about.techCmsDesc": "We implement content platforms designed for teams that need autonomy, organization and scalability. We optimize digital administration so that daily operations are more efficient and professional.",
    "about.techCmsStack": "WordPress - Headless CMS - Webflow - Shopify",
    "about.ctaSectionLabel": "Strategic closing",
    "about.ctaTitle": "We Are the AI Agency for Enterprises",
    "about.ctaDesc": "Connect with a specialized advisor and discover how we can transform your business with custom artificial intelligence solutions.",
    "about.techCapability": "Technological capability",
    "about.institutionalProfile": "Institutional profile",
    "about.competitiveAdvantage": "Competitive advantage",
    "about.founder1Label": "Vision, strategy and growth",
    "about.founder1Bio": "As CEO & Founder of Codifikai, I lead a vision focused on building digital solutions that connect innovation, execution and business results. I firmly believe that technology should feel close, useful and capable of driving real evolution for every company that trusts us.",
    "about.founder1Quote": "We don't just build software: we build trust, evolution and real growth opportunities.",
    "about.founder2Label": "Strategy, expansion and commercial direction",
    "about.founder2Bio": "As Co-Founder & Strategy Director of Codifikai, I drive a vision focused on sustainable growth, strategic clarity and building solid relationships with each client. My focus is on aligning business, positioning and execution so that each solution generates real impact and strengthens brand evolution.",
    "about.founder2Quote": "A well-directed strategy turns ideas into opportunities and opportunities into real growth.",
    "about.founder3Label": "Commercial development and alliances",
    "about.founder3Bio": "As Business Development Manager, he leads account prospecting, value proposition design and strengthening relationships with partners and clients. His focus connects business needs with scalable technology solutions.",
    "about.founder3Quote": "Every solid commercial relationship is a gateway to projects that transform companies.",
    
    // CTA
    "cta.title": "Transform your business with AI",
    "cta.subtitle": "Schedule a free consultation and discover how artificial intelligence can boost your company.",
    "cta.button": "Schedule Consultation",
    "cta.available": "Available now",
    
    // Footer
    "footer.description": "Artificial Intelligence Agency specialized in development, marketing, and business automation.",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.rights": "All rights reserved.",
    "footer.ctaTitle": "Ready to work together",
    "footer.ctaButton": "Let's talk",
    "footer.linksHeading": "Links",
    "footer.writeUs": "Write to us",
    "footer.emailJobs": "Careers & talent",
    "footer.linkAbout": "About us",
    "footer.linkServices": "Services",
    "footer.linkBlog": "Blog",
    "footer.linkSecurity": "Security and data protection policy",
    
    // Process
    "process.title": "Our Process",
    "process.subtitle": "Agile methodology for extraordinary results",
    "process.step1.title": "Discovery",
    "process.step1.desc": "We analyze your business, objectives, and challenges to create a personalized strategy.",
    "process.step2.title": "Strategy",
    "process.step2.desc": "We design the solution architecture and define the implementation roadmap.",
    "process.step3.title": "Development",
    "process.step3.desc": "We build the solution with cutting-edge technology and agile methodologies.",
    "process.step4.title": "Launch",
    "process.step4.desc": "We deploy, monitor, and optimize to ensure continuous success.",
    
    // Testimonials
    "testimonials.title": "What Our Clients Say",
    "testimonials.subtitle": "Results that speak for themselves",
    
    // Team
    "team.label": "Leadership",
    "team.title": "Our Team",
    "team.subtitle": "Experts in technology and innovation",
    "team.viewProfile": "View profile",
    "team.jhoanBio": "Leads Codifikai's vision with focus on growth, execution and digital solutions aligned with business.",
    "team.jhonBio": "Drives strategy, commercial expansion and direction of initiatives with real and sustainable impact.",
    "team.roleBDM": "Business Development Manager",
    "team.victorBio": "Drives strategic alliances, new business opportunities and Codifikai's expansion in key markets, aligning client relationships with product vision and growth.",
    
    // Partners
    "partners.title": "Brands That Trust Us",
    "partners.subtitle": "Commercial representations and strategic alliances",
    
    // Case Studies
    "cases.label": "Featured cases",
    "cases.title": "Case Studies",
    "cases.subtitle": "Projects that generate real impact",
    "cases.viewAll": "View all cases",

    // Globe / Global reach
    "globe.label": "Global reach",
    "globe.badge": "From Colombia to the world",
    "globe.title": "Projects and clients across multiple continents",
    "globe.subtitle": "We develop software, automation and AI solutions for companies in the United States, Europe, Asia and beyond. Connecting technological vision with global execution.",
    "globe.fromColombia": "From Colombia",
    "globe.towards": "to",
    "globe.usaDesc": "Software projects, e-commerce and automation for clients in the United States. Web development, apps and AI solutions.",
    "globe.europaDesc": "Digital platforms and marketing strategies for the European market. Regulatory compliance and scalability.",
    "globe.japonDesc": "Technology solutions and digital sourcing for the Asian market. Focus on quality and precision.",
    "globe.chinaDesc": "Software development and international trade solutions. Integration with Asian digital ecosystems.",
    "globe.canadaDesc": "Software projects and digital transformation for clients in North America. Scalable platforms.",
    "globe.mexicoDesc": "Software development and digital solutions for the Mexican market. E-commerce, apps and automation.",
    "globe.brasilDesc": "Platforms and software for the Brazilian market. Integration with Latin American ecosystems.",
    "globe.argentinaDesc": "Software solutions and digital transformation for companies in the Southern Cone.",
    "globe.chileDesc": "Technology development and AI solutions for the Chilean market. Mining, retail and services.",
    "globe.peruDesc": "Digital projects and software for Peruvian companies. Commerce and logistics.",
    "globe.uaeDesc": "Technology solutions for the Gulf. E-commerce, fintech and B2B platforms.",
    "globe.indiaDesc": "Software development and technology outsourcing. Integration with global teams.",
    "globe.coreaDesc": "Technology and digital solutions for the Korean market. Innovation and precision.",
    "globe.australiaDesc": "Software and AI solutions for the Australian market. Commerce and services.",
    "globe.statusActive": "Active market",
    "globe.statusExpansion": "Expanding",
    "globe.statusStrategic": "Strategic market",
    "globe.statusGrowth": "Growing",
    "globe.centerColombia": "Center on Colombia",
    "globe.usa": "United States",
    "globe.europa": "Europe",
    "globe.japon": "Japan",
    "globe.china": "China",
    "globe.canada": "Canada",
    "globe.mexico": "Mexico",
    "globe.brasil": "Brazil",
    "globe.argentina": "Argentina",
    "globe.chile": "Chile",
    "globe.peru": "Peru",
    "globe.uae": "UAE",
    "globe.india": "India",
    "globe.corea": "South Korea",
    "globe.australia": "Australia",
    "globe.colombiaGlobeLabel": "Colombia · HUB",
    "globe.techMetaColombia": "HUB_CODIFIKAI · region=CO · lat=4.571 · lng=-74.297 · role=primary_edge · TLS=1.3 · status=online",
    "globe.techMetaUsa": "NODE=US-NOAM · uplink=CO⇄US · lat=39.83 · stack=Next.js|Node · cloud=AWS · svc=web·apps·AI·e-commerce · api=REST|GraphQL",
    "globe.techMetaMexico": "NODE=MX-LATAM · uplink=CO⇄MX · stack=React|Nest · svc=web·apps·automation · deploy=multi-region",
    "globe.techMetaCanada": "NODE=CA-NOAM · uplink=CO⇄CA · stack=TS|Python · svc=platforms·integration · compliance=PIPEDA",
    "globe.techMetaBrasil": "NODE=BR-LATAM · uplink=CO⇄BR · stack=Node|React · locale=pt-BR · svc=e-commerce·APIs",
    "globe.techMetaArgentina": "NODE=AR-SOUTH · uplink=CO⇄AR · stack=web|mobile · svc=digital transformation",
    "globe.techMetaChile": "NODE=CL-ANDES · uplink=CO⇄CL · stack=AI|analytics · vertical=retail·mining",
    "globe.techMetaPeru": "NODE=PE-ANDES · uplink=CO⇄PE · svc=logistics·commerce · integration=ERP",
    "globe.techMetaEuropa": "NODE=EU-CENTRAL · uplink=CO⇄EU · stack=Next|headless · policy=GDPR · multi-tenant",
    "globe.techMetaUae": "NODE=AE-GCC · uplink=CO⇄AE · svc=fintech·B2B · latency=optimized",
    "globe.techMetaIndia": "NODE=IN-APAC · uplink=CO⇄IN · model=distributed teams · stack=full-stack",
    "globe.techMetaChina": "NODE=CN-APAC · uplink=CO⇄CN · integration=trade·APIs · i18n=zh",
    "globe.techMetaJapon": "NODE=JP-APAC · uplink=CO⇄JP · stack=quality-first · svc=B2B",
    "globe.techMetaCorea": "NODE=KR-APAC · uplink=CO⇄KR · stack=web·apps · innovation=high",
    "globe.techMetaAustralia": "NODE=AU-APAC · uplink=CO⇄AU · svc=software·AI · region=Oceania",

    // Legal (privacy / terms)
    "legal.backToHome": "Back to home",
    "legal.contactHint": "For questions about these documents:",
    "legal.privacy.title": "Privacy policy",
    "legal.privacy.updated": "Last updated: March 2026",
    "legal.privacy.s1.title": "1. Data controller",
    "legal.privacy.s1.body": "The controller of personal data is Codifikai, hereinafter «Codifikai», with address for notifications in Colombia and contact email codifikai@gmail.com.\n\nUse of this website and the provision of services may involve processing of personal data in accordance with applicable law in Colombia (Law 1581 of 2012 and related rules) and, where relevant, the European data protection framework.",
    "legal.privacy.s2.title": "2. Data we may process",
    "legal.privacy.s2.body": "Depending on how you interact with us, we may process identification and contact data (name, email, phone, company), browsing and technical data (IP address, device type, browser, pages visited) and, where applicable, information you voluntarily provide via forms or communications.\n\nWe do not request specially protected data unless strictly necessary and with your explicit consent where required by law.",
    "legal.privacy.s3.title": "3. Purposes and legal basis",
    "legal.privacy.s3.body": "We process data to: manage enquiries and contact requests; deliver and improve our software development, automation and artificial intelligence services; send communications related to the contractual or pre-contractual relationship where there is legitimate interest or consent; comply with legal obligations; and ensure site security and service continuity.\n\nThe legal basis may be consent, performance of a contract, legitimate interest where applicable, or compliance with legal obligations, depending on each processing activity.",
    "legal.privacy.s4.title": "4. Retention and disclosure to third parties",
    "legal.privacy.s4.body": "We retain data for as long as necessary to fulfil the purposes described and legal obligations. After that period, we delete or anonymise it where possible.\n\nWe may use hosting, analytics, email or cloud providers who act as processors under appropriate contractual safeguards. We do not sell your personal data.",
    "legal.privacy.s5.title": "5. Your rights",
    "legal.privacy.s5.body": "You may exercise rights to access, update, rectify and delete your data, revoke consent, obtain proof of authorisation, access your data free of charge, lodge complaints with the competent authority, and others provided under Law 1581 of 2012 and its regulations.\n\nTo exercise your rights, write to codifikai@gmail.com stating the right you wish to exercise and your identity. We may request reasonable additional information to verify your identity.",
    "legal.privacy.s6.title": "6. Cookies, security and changes",
    "legal.privacy.s6.body": "This site may use cookies and similar technologies for analytics and to improve the experience. You can configure your browser to reject cookies, although some features may be limited.\n\nWe apply reasonable technical and organisational measures to protect information. No system is 100% secure.\n\nWe may change this policy; the current version will be published on this page with the update date shown above.",

    "legal.terms.title": "Terms and conditions of use",
    "legal.terms.updated": "Last updated: March 2026",
    "legal.terms.s1.title": "1. Acceptance",
    "legal.terms.s1.body": "Access to and use of Codifikai’s website (the «Site») implies acceptance of these terms and conditions. If you do not agree, you must not use the Site.\n\nCodifikai may modify this document at any time. Changes take effect from publication on the web.",
    "legal.terms.s2.title": "2. Identification and services",
    "legal.terms.s2.body": "Codifikai provides professional software development, automation, artificial intelligence and related digital solutions, as agreed in each proposal or individual contract.\n\nSite content is general and informational. It does not constitute legal advice or a guarantee of specific results unless expressly agreed in writing.",
    "legal.terms.s3.title": "3. Permitted use",
    "legal.terms.s3.body": "You agree to use the Site lawfully, without infringing third-party rights, without introducing malware or engaging in activities that may damage, disrupt or overload systems.\n\nUnauthorized commercial reproduction of Site content, abusive automated extraction (scraping) and any use that violates applicable law or good faith are prohibited.",
    "legal.terms.s4.title": "4. Intellectual property",
    "legal.terms.s4.body": "Text, trademarks, logos, design, code and other elements of the Site are protected under applicable law. Rights in project deliverables are governed by the relevant contract with each client.\n\nUnless expressly licensed, no right to use Site materials is granted beyond personal browsing.",
    "legal.terms.s5.title": "5. Limitation of liability",
    "legal.terms.s5.body": "The Site is provided «as is» and «as available». To the extent permitted by law, Codifikai shall not be liable for indirect damages, lost profits, data loss or interruptions arising from use or inability to use the Site.\n\nLinks to third-party sites are for information only; Codifikai does not control those sites or assume responsibility for their content.",
    "legal.terms.s6.title": "6. Governing law and contact",
    "legal.terms.s6.body": "Unless mandatory law provides otherwise, relations arising from use of the Site shall be governed by the laws of the Republic of Colombia. Disputes shall be submitted to the competent courts in Colombia, unless special rules apply.\n\nFor questions about these terms: codifikai@gmail.com.",

    // Contact floating
    "contact.title": "Let's Talk",
    "contact.subtitle": "We're ready to help transform your business",
    "contact.whatsapp": "Instant response",
    "contact.email": "codifikai@gmail.com",
    "contact.schedule": "Schedule Call",
    "contact.scheduleDesc": "Free consultation",
    "contact.cta": "See more options",

    // Services Preview
    "servicesPreview.label": "Services",
    "servicesPreview.title": "Solutions designed to grow with you",
    "servicesPreview.subtitle": "We combine speed, strategy and technological execution to build digital solutions that improve processes, strengthen brands and generate sustainable growth.",
    "servicesPreview.lowcode": "Low Code",
    "servicesPreview.lowcodeDesc": "We develop agile digital solutions for companies that need to launch, validate and optimize quickly, without sacrificing visual quality or professional structure.",
    "servicesPreview.software": "Software Development",
    "servicesPreview.softwareDesc": "We create platforms, systems and custom products with solid architecture, scalable approach and implementation aligned with your business processes.",
    "servicesPreview.marketing": "Digital Marketing (SEO)",
    "servicesPreview.marketingDesc": "We design positioning and digital visibility strategies to attract quality traffic, strengthen your online presence and generate sustainable business opportunities.",
    "servicesPreview.contactLabel": "Contact us",
    "servicesPreview.contactTitle": "Do you need any of these services?",
    "servicesPreview.contactCta": "Contact us",

    // Technologies Preview
    "techPreview.label": "Tools and stack",
    "techPreview.title": "The right technology to build solid solutions",
    "techPreview.subtitle": "We work with a modern and strategic stack to develop digital products, automations and platforms ready to grow with your business.",
    "techPreview.viewTools": "View tools",
    "techPreview.frontend": "Frontend",
    "techPreview.frontendDesc": "Modern, fast interfaces focused on user experience.",
    "techPreview.backend": "Backend",
    "techPreview.backendDesc": "Stable, secure architectures ready to scale.",
    "techPreview.datascience": "Data Science",
    "techPreview.datascienceDesc": "Models, analysis and automation based on useful information.",
    "techPreview.cms": "Content Management",
    "techPreview.cmsDesc": "Flexible platforms to manage and evolve digital products.",

    // Company Intro
    "companyIntro.label": "Who we are",
    "companyIntro.badge": "Technology partners for evolving brands",
    "companyIntro.title": "We turn ideas and processes into digital solutions with real impact.",
    "companyIntro.subtitle": "Software, automation and AI for business growth—from strategy to execution, with products built to scale.",
    "companyIntro.pillar1": "Custom software development",
    "companyIntro.pillar2": "Automation and AI solutions",
    "companyIntro.pillar3": "Digital strategy focused on growth",
    "companyIntro.stats1": "cumulative deliveries and go-lives",
    "companyIntro.stats2": "industries and verticals served",
    "companyIntro.stats3": "client retention and renewal",
    "companyIntro.cta": "Learn about the company",
    "companyIntro.leadership": "Leadership and execution",
    "companyIntro.cardTag": "We build solutions that connect technology, user experience and business growth.",

    // Strategy
    "strategy.label": "Our strategy",
    "strategy.title": "Business strategy powered by AI",
    "strategy.subtitle": "We combine business experience with cutting-edge technology to create solutions that transform operations and generate sustainable growth.",
    "strategy.fast": "Fast Implementation",
    "strategy.fastDesc": "Agile methodologies that deliver results in weeks, not months.",
    "strategy.security": "Enterprise Security",
    "strategy.securityDesc": "Enterprise-level security protocols to protect your data.",
    "strategy.scale": "Scalability",
    "strategy.scaleDesc": "Architectures designed to grow with your business without limits.",
    "strategy.roi": "Guaranteed ROI",
    "strategy.roiDesc": "We constantly measure and optimize to maximize your return.",
    "strategy.metricsTitle": "Success Metrics",
    "strategy.metrics1": "Projects delivered on time",
    "strategy.metrics2": "Client satisfaction",
    "strategy.metrics3": "Integrations completed",
    "strategy.iso": "ISO 27001 Certified",
    "strategy.gcp": "Google Cloud Partner",
    "strategy.aws": "AWS Certified",

    // Stats
    "stats.label": "Results and trust",
    "stats.generated": "Generated for clients",
    "stats.reduction": "Average cost reduction",
    "stats.roi": "Average ROI in 6 months",
    "stats.support": "Continuous support",
    "stats.testimonial1": "Codifikai transformed our sales operation with AI. The results exceeded our expectations.",
    "stats.testimonial2": "The automation implemented saved us over 200 hours monthly on repetitive tasks.",
    "stats.testimonial3": "An exceptional team that understands both technology and business needs.",

    // Footer links
    "footer.servicesWeb": "AI Websites",
    "footer.servicesApps": "AI Apps",
    "footer.servicesSoftware": "AI Software",
    "footer.servicesMarketing": "AI Marketing",
    "footer.servicesAutomation": "Automation",
    "footer.companyAbout": "About",
    "footer.companyCases": "Case Studies",
    "footer.companyBlog": "Blog",
    "footer.companyCareers": "Careers",
    "footer.companyContact": "Contact",

    // Casos de éxito
    "casesPage.label": "Portfolio",
    "casesPage.title": "Case Studies",
    "casesPage.subtitle": "Projects we have delivered for clients in international trade, marketplaces, logistics and experiential marketing. Click each card to visit the site.",
    "casesPage.visitSite": "View live site",
    "casesPage.ctaTitle": "Want your project to be the next success story?",
    "casesPage.ctaButton": "Let's talk about your project",

    // Features
    "features.strategy": "Strategy",
    "features.strategyDesc": "We design customized solutions based on deep analysis of your business and objectives.",
    "features.planning": "Planning",
    "features.planningDesc": "Agile methodologies and clear roadmaps to execute projects efficiently.",
    "features.growth": "Growth",
    "features.growthDesc": "Scalable solutions that evolve with your company and generate measurable results.",
  },
}

const initialState: LanguageProviderState = {
  language: "es",
  setLanguage: () => null,
  t: () => "",
}

const LanguageProviderContext = createContext<LanguageProviderState>(initialState)

export function LanguageProvider({
  children,
  defaultLanguage = "es",
  storageKey = "codifikai-language",
  ...props
}: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(defaultLanguage)

  useEffect(() => {
    const stored = localStorage.getItem(storageKey) as Language | null
    if (stored) {
      setLanguage(stored)
    }
  }, [storageKey])

  useEffect(() => {
    localStorage.setItem(storageKey, language)
    document.documentElement.lang = language
  }, [language, storageKey])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  const value = {
    language,
    setLanguage,
    t,
  }

  return (
    <LanguageProviderContext.Provider {...props} value={value}>
      {children}
    </LanguageProviderContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
